# Generated by Django 5.1.6 on 2025-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_link',
            new_name='hero_cta_link',
        ),
    ]
