# Generated by Django 5.1.6 on 2025-02-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footer'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='FooterText',
        ),
    ]
